//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace artiktamam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car_Tablo
    {
        public int CarId { get; set; }
        public Nullable<int> CarMarkaKod { get; set; }
        public Nullable<int> CarModelKod { get; set; }
        public Nullable<decimal> CarFiyat { get; set; }
        public string CarPhoto { get; set; }
    
        public virtual Marka_Tablo Marka_Tablo { get; set; }
        public virtual Model_Table Model_Table { get; set; }
    }
}
