//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace artiktamam.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class galeriEntities7 : DbContext
    {
        public galeriEntities7()
            : base("name=galeriEntities7")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Car_Tablo> Car_Tablo { get; set; }
        public virtual DbSet<Marka_Tablo> Marka_Tablo { get; set; }
        public virtual DbSet<Model_Table> Model_Table { get; set; }
        public virtual DbSet<Roles_Tablo> Roles_Tablo { get; set; }
        public virtual DbSet<SatinalmaGecmisi_Table> SatinalmaGecmisi_Table { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<UserRoleMapping> UserRoleMapping { get; set; }
        public virtual DbSet<Users_Tablo> Users_Tablo { get; set; }
        public virtual DbSet<ShowCars> ShowCars { get; set; }
    }
}
