//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace artiktamam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShowCars
    {
        public int ID { get; set; }
        public string MarkaName { get; set; }
        public string ModelName { get; set; }
        public Nullable<decimal> CarFiyat { get; set; }
        public string CarPhoto { get; set; }
    }
}
